language: csharp

matrix:
  allow_failures:
    - os: osx

  include:
    - os: linux
      # dist: xenial # 16.04
      dist: trusty # 14.04
      sudo: required
      dotnet: 2.1.104

    - os: linux
      services:
        - docker
      before_script:
        - ./docko build

      script:
        - ./docko run --rm cec bash -c "./run test"

    # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    - os: osx # OSX 10.13
      osx_image: xcode9.3
      dotnet: 2.1.104

before_script:
  - uname -a
  - bash -c "./run init"

script:
 - bash -c "./run restore"
 - bash -c "./run test"
