language: csharp
# mono: none

matrix:
  include:
    - os: linux
      # dist: xenial # 16.04
      dist: trusty # 14.04
      sudo: required
      dotnet: 2.1.104

    # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    # - os: osx # OSX 10.13
    #   osx_image: xcode9.3
    #   dotnet: 2.0.0

before_script:
  - uname -a
  - bash -c "./run init"

script:
 - bash -c "./run test:restore"
 - bash -c "./run test"
