language: csharp
mono: none

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: xenial
      sudo: required
      dotnet: 2.0.0

    # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    - os: osx # OSX 10.13
      osx_image: xcode9.3
      dotnet: 2.0.0

before_script:
  - ./run init

script:
 - ./run test:restore
 - ./run test
